name: keep alive 
on:
    workflow_run:
      workflows: ["run"]  # 指定主工作流名
      types:
        - completed  # 主工作流完成后触发
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
